LOG_FILE="/opt/var/log/keensnap.log"
LOG_MAX_SIZE_KB=512
PATH_SNAPD="/opt/root/KeenSnap/keensnap-init"
CRON_SCHEDULE="0 3 * * *"
SELECTED_DRIVE=""
BOT_TOKEN=""
CHAT_ID=""
BACKUP_STARTUP_CONFIG=false
BACKUP_FIRMWARE=false
BACKUP_ENTWARE=false
ENTWARE_EXCLUDE=""
BACKUP_WG_PRIVATE_KEY=false
DELETE_LOCAL_ARCHIVE_AFTER_BACKUP=false
ARCHIVE_PASSWORD=""
PROXY_INTERFACE=""
TG_PROXY=""
UPLOAD_METHOD=""
GD_CLIENT_ID=""
GD_CLIENT_SECRET=""
GD_REFRESH_TOKEN=""
GD_FOLDER_ID=""
WD_URL=""
WD_USERNAME=""
WD_PASSWORD=""
WD_INSECURE=false
S3_ENDPOINT=""
S3_BUCKET_NAME=""
S3_KEY=""
S3_SECRET=""
S3_PREFIX=""
S3_RETAIN_BACKUPS=0
RETAIN_ARCHIVES_DAYS=0
AUTO_UPDATE=true
HASHTAG="#KeenSnap"
